/********************************************************************
* dicts/Linux/TPhysClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TPhysClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPhysClassDict();
extern void G__cpp_setup_inheritanceTPhysClassDict();
extern void G__cpp_setup_typetableTPhysClassDict();
extern void G__cpp_setup_memvarTPhysClassDict();
extern void G__cpp_setup_globalTPhysClassDict();
extern void G__cpp_setup_memfuncTPhysClassDict();
extern void G__cpp_setup_funcTPhysClassDict();
extern void G__set_cpp_environmentTPhysClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPhysClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPhysClassDictLN_TClass;
extern G__linked_taginfo G__TPhysClassDictLN_TBuffer;
extern G__linked_taginfo G__TPhysClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TPhysClassDictLN_TObject;
extern G__linked_taginfo G__TPhysClassDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysClassDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TPhysClassDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysClassDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TPhysClassDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TPhysClassDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TPhysClassDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPhysClassDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TPhysClassDictLN_TClasTool;
extern G__linked_taginfo G__TPhysClassDictLN_TPhysClass;

/* STUB derived class for protected member access */
