/********************************************************************
* dicts/Linux64RHEL7/TCLASCorrectionsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TCLASCorrectionsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCLASCorrectionsDict();
extern void G__cpp_setup_inheritanceTCLASCorrectionsDict();
extern void G__cpp_setup_typetableTCLASCorrectionsDict();
extern void G__cpp_setup_memvarTCLASCorrectionsDict();
extern void G__cpp_setup_globalTCLASCorrectionsDict();
extern void G__cpp_setup_memfuncTCLASCorrectionsDict();
extern void G__cpp_setup_funcTCLASCorrectionsDict();
extern void G__set_cpp_environmentTCLASCorrectionsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCLASCorrections.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCLASCorrectionsDictLN_TClass;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TBuffer;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMemberInspector;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TObject;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsDictLN_TCLASCorrections;

/* STUB derived class for protected member access */
