/********************************************************************
* dicts/Linux64RHEL7/TEnergyLossDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TEnergyLossDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEnergyLossDict();
extern void G__cpp_setup_inheritanceTEnergyLossDict();
extern void G__cpp_setup_typetableTEnergyLossDict();
extern void G__cpp_setup_memvarTEnergyLossDict();
extern void G__cpp_setup_globalTEnergyLossDict();
extern void G__cpp_setup_memfuncTEnergyLossDict();
extern void G__cpp_setup_funcTEnergyLossDict();
extern void G__set_cpp_environmentTEnergyLossDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TEnergyLoss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEnergyLossDictLN_TClass;
extern G__linked_taginfo G__TEnergyLossDictLN_TBuffer;
extern G__linked_taginfo G__TEnergyLossDictLN_TMemberInspector;
extern G__linked_taginfo G__TEnergyLossDictLN_TObject;
extern G__linked_taginfo G__TEnergyLossDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEnergyLossDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEnergyLossDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEnergyLossDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEnergyLossDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TEnergyLossDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TEnergyLossDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TEnergyLossDictLN_TVector3;
extern G__linked_taginfo G__TEnergyLossDictLN_TLorentzVector;
extern G__linked_taginfo G__TEnergyLossDictLN_TFuncIntercept;
extern G__linked_taginfo G__TEnergyLossDictLN_TFuncLoss;
extern G__linked_taginfo G__TEnergyLossDictLN_TEnergyLoss;

/* STUB derived class for protected member access */
