/********************************************************************
* dicts/Linux64RHEL7/TFuncLossDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TFuncLossDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFuncLossDict();
extern void G__cpp_setup_inheritanceTFuncLossDict();
extern void G__cpp_setup_typetableTFuncLossDict();
extern void G__cpp_setup_memvarTFuncLossDict();
extern void G__cpp_setup_globalTFuncLossDict();
extern void G__cpp_setup_memfuncTFuncLossDict();
extern void G__cpp_setup_funcTFuncLossDict();
extern void G__set_cpp_environmentTFuncLossDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TFuncLoss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFuncLossDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFuncLossDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFuncLossDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFuncLossDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFuncLossDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFuncLossDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFuncLossDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFuncLossDictLN_TSpline3;
extern G__linked_taginfo G__TFuncLossDictLN_TFuncLoss;

/* STUB derived class for protected member access */
