/********************************************************************
* dicts/Linux64RHEL7/TDC0ClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TDC0ClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTDC0ClassDict();
extern void G__cpp_setup_inheritanceTDC0ClassDict();
extern void G__cpp_setup_typetableTDC0ClassDict();
extern void G__cpp_setup_memvarTDC0ClassDict();
extern void G__cpp_setup_globalTDC0ClassDict();
extern void G__cpp_setup_memfuncTDC0ClassDict();
extern void G__cpp_setup_funcTDC0ClassDict();
extern void G__set_cpp_environmentTDC0ClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDC0Class.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TDC0ClassDictLN_TClass;
extern G__linked_taginfo G__TDC0ClassDictLN_TBuffer;
extern G__linked_taginfo G__TDC0ClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TDC0ClassDictLN_TObject;
extern G__linked_taginfo G__TDC0ClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TDC0ClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDC0ClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TDC0ClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDC0ClassDictLN_TDC0Class;

/* STUB derived class for protected member access */
