//
// File generated by /u/apps/root/5.34.36/root/bin/rootcint at Tue Jan  9 15:26:45 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinux64RHEL7dITHBLAClassDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "THBLAClassDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void THBLAClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_THBLAClass(void *p = 0);
   static void *newArray_THBLAClass(Long_t size, void *p);
   static void delete_THBLAClass(void *p);
   static void deleteArray_THBLAClass(void *p);
   static void destruct_THBLAClass(void *p);
   static void streamer_THBLAClass(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::THBLAClass*)
   {
      ::THBLAClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::THBLAClass >(0);
      static ::ROOT::TGenericClassInfo 
         instance("THBLAClass", ::THBLAClass::Class_Version(), "./THBLAClass.h", 24,
                  typeid(::THBLAClass), ::ROOT::DefineBehavior(ptr, ptr),
                  &::THBLAClass::Dictionary, isa_proxy, 0,
                  sizeof(::THBLAClass) );
      instance.SetNew(&new_THBLAClass);
      instance.SetNewArray(&newArray_THBLAClass);
      instance.SetDelete(&delete_THBLAClass);
      instance.SetDeleteArray(&deleteArray_THBLAClass);
      instance.SetDestructor(&destruct_THBLAClass);
      instance.SetStreamerFunc(&streamer_THBLAClass);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::THBLAClass*)
   {
      return GenerateInitInstanceLocal((::THBLAClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::THBLAClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr THBLAClass::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *THBLAClass::Class_Name()
{
   return "THBLAClass";
}

//______________________________________________________________________________
const char *THBLAClass::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THBLAClass*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THBLAClass::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THBLAClass*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THBLAClass::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THBLAClass*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THBLAClass::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THBLAClass*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void THBLAClass::Streamer(TBuffer &R__b)
{
   // Stream an object of class THBLAClass.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> trk_pln;
      R__b >> x;
      R__b >> y;
      R__b >> z;
      R__b >> tlen;
      R__b >> dc1;
      R__b >> stat;
      R__b >> wire;
      R__b >> dtime;
      R__b >> alpha;
      R__b >> wlen;
      R__b >> sgdoca;
      R__b >> fitdoca;
      R__b >> sector;
      R__b.CheckByteCount(R__s, R__c, THBLAClass::IsA());
   } else {
      R__c = R__b.WriteVersion(THBLAClass::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << trk_pln;
      R__b << x;
      R__b << y;
      R__b << z;
      R__b << tlen;
      R__b << dc1;
      R__b << stat;
      R__b << wire;
      R__b << dtime;
      R__b << alpha;
      R__b << wlen;
      R__b << sgdoca;
      R__b << fitdoca;
      R__b << sector;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void THBLAClass::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class THBLAClass.
      TClass *R__cl = ::THBLAClass::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trk_pln", &trk_pln);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "z", &z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tlen", &tlen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dc1", &dc1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "stat", &stat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wire", &wire);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtime", &dtime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "alpha", &alpha);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wlen", &wlen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sgdoca", &sgdoca);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fitdoca", &fitdoca);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sector", &sector);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_THBLAClass(void *p) {
      return  p ? new(p) ::THBLAClass : new ::THBLAClass;
   }
   static void *newArray_THBLAClass(Long_t nElements, void *p) {
      return p ? new(p) ::THBLAClass[nElements] : new ::THBLAClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_THBLAClass(void *p) {
      delete ((::THBLAClass*)p);
   }
   static void deleteArray_THBLAClass(void *p) {
      delete [] ((::THBLAClass*)p);
   }
   static void destruct_THBLAClass(void *p) {
      typedef ::THBLAClass current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_THBLAClass(TBuffer &buf, void *obj) {
      ((::THBLAClass*)obj)->::THBLAClass::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::THBLAClass

/********************************************************
* dicts/Linux64RHEL7/THBLAClassDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTHBLAClassDict();

extern "C" void G__set_cpp_environmentTHBLAClassDict() {
  G__cpp_reset_tagtableTHBLAClassDict();
}
#include <new>
extern "C" int G__cpp_dllrevTHBLAClassDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THBLAClass */
static int G__THBLAClassDict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THBLAClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THBLAClass[n];
     } else {
       p = new((void*) gvp) THBLAClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THBLAClass;
     } else {
       p = new((void*) gvp) THBLAClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THBLAClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new THBLAClass((THBLAClass*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) THBLAClass((THBLAClass*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THBLAClass*) G__getstructoffset())->GetTrk_pln());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetTlen());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THBLAClass*) G__getstructoffset())->GetDc1());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THBLAClass*) G__getstructoffset())->GetStat());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THBLAClass*) G__getstructoffset())->GetWire());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetDtime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetAlpha());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetWlen());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetSgdoca());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THBLAClass*) G__getstructoffset())->GetFitDoca());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THBLAClass*) G__getstructoffset())->GetSector());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THBLAClass*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) THBLAClass::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THBLAClass::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) THBLAClass::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      THBLAClass::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THBLAClass*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THBLAClass::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THBLAClass::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THBLAClass::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__THBLAClassDict_184_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THBLAClass::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__THBLAClassDict_184_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   THBLAClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new THBLAClass(*(THBLAClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THBLAClass G__TTHBLAClass;
static int G__THBLAClassDict_184_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (THBLAClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((THBLAClass*) (soff+(sizeof(THBLAClass)*i)))->~G__TTHBLAClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (THBLAClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((THBLAClass*) (soff))->~G__TTHBLAClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__THBLAClassDict_184_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THBLAClass* dest = (THBLAClass*) G__getstructoffset();
   *dest = *(THBLAClass*) libp->para[0].ref;
   const THBLAClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THBLAClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTHBLAClassDict {
 public:
  G__Sizep2memfuncTHBLAClassDict(): p(&G__Sizep2memfuncTHBLAClassDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTHBLAClassDict::*p)();
};

size_t G__get_sizep2memfuncTHBLAClassDict()
{
  G__Sizep2memfuncTHBLAClassDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTHBLAClassDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass))) {
     THBLAClass *G__Lderived;
     G__Lderived=(THBLAClass*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass),G__get_linked_tagnum(&G__THBLAClassDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTHBLAClassDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__THBLAClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THBLAClass */
static void G__setup_memvarTHBLAClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass));
   { THBLAClass *p; p=(THBLAClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->trk_pln)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trk_pln=",0,"id of DC hit");
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x=",0,"tdc value");
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tlen)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tlen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dc1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dc1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->stat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"stat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->wire)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"wire=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtime)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->alpha)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"alpha=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->wlen)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"wlen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sgdoca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"sgdoca=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fitdoca)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"fitdoca=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sector)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"sector=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__THBLAClassDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTHBLAClassDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHBLAClass(void) {
   /* THBLAClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass));
   G__memfunc_setup("THBLAClass",865,G__THBLAClassDict_184_0_1, 105, G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("THBLAClass",865,G__THBLAClassDict_184_0_2, 105, G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass), -1, 0, 1, 1, 1, 0, "U 'THBLAClass' - 0 - TmpHBLA", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrk_pln",1018,G__THBLAClassDict_184_0_3, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetX",376,G__THBLAClassDict_184_0_4, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetY",377,G__THBLAClassDict_184_0_5, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZ",378,G__THBLAClassDict_184_0_6, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTlen",691,G__THBLAClassDict_184_0_7, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDc1",504,G__THBLAClassDict_184_0_8, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStat",700,G__THBLAClassDict_184_0_9, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWire",695,G__THBLAClassDict_184_0_10, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDtime",787,G__THBLAClassDict_184_0_11, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAlpha",774,G__THBLAClassDict_184_0_12, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWlen",694,G__THBLAClassDict_184_0_13, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSgdoca",881,G__THBLAClassDict_184_0_14, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFitDoca",954,G__THBLAClassDict_184_0_15, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSector",912,G__THBLAClassDict_184_0_16, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__THBLAClassDict_184_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__THBLAClassDict_184_0_18, 85, G__get_linked_tagnum(&G__THBLAClassDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&THBLAClass::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__THBLAClassDict_184_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THBLAClass::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__THBLAClassDict_184_0_20, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&THBLAClass::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__THBLAClassDict_184_0_21, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&THBLAClass::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__THBLAClassDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__THBLAClassDict_184_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__THBLAClassDict_184_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THBLAClass::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__THBLAClassDict_184_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THBLAClass::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__THBLAClassDict_184_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THBLAClass::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__THBLAClassDict_184_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THBLAClass::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("THBLAClass", 865, G__THBLAClassDict_184_0_30, (int) ('i'), G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass), -1, 0, 1, 1, 1, 0, "u 'THBLAClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~THBLAClass", 991, G__THBLAClassDict_184_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__THBLAClassDict_184_0_32, (int) ('u'), G__get_linked_tagnum(&G__THBLAClassDictLN_THBLAClass), -1, 1, 1, 1, 1, 0, "u 'THBLAClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTHBLAClassDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTHBLAClassDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTHBLAClassDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__THBLAClassDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__THBLAClassDictLN_THBLAClass = { "THBLAClass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTHBLAClassDict() {
  G__THBLAClassDictLN_TClass.tagnum = -1 ;
  G__THBLAClassDictLN_TBuffer.tagnum = -1 ;
  G__THBLAClassDictLN_TMemberInspector.tagnum = -1 ;
  G__THBLAClassDictLN_TObject.tagnum = -1 ;
  G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__THBLAClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__THBLAClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__THBLAClassDictLN_THBLAClass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTHBLAClassDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__THBLAClassDictLN_THBLAClass),sizeof(THBLAClass),-1,62720,"Class for accessing the HBLA: Time of Flight.",G__setup_memvarTHBLAClass,G__setup_memfuncTHBLAClass);
}
extern "C" void G__cpp_setupTHBLAClassDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTHBLAClassDict()");
  G__set_cpp_environmentTHBLAClassDict();
  G__cpp_setup_tagtableTHBLAClassDict();

  G__cpp_setup_inheritanceTHBLAClassDict();

  G__cpp_setup_typetableTHBLAClassDict();

  G__cpp_setup_memvarTHBLAClassDict();

  G__cpp_setup_memfuncTHBLAClassDict();
  G__cpp_setup_globalTHBLAClassDict();
  G__cpp_setup_funcTHBLAClassDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTHBLAClassDict();
  return;
}
class G__cpp_setup_initTHBLAClassDict {
  public:
    G__cpp_setup_initTHBLAClassDict() { G__add_setup_func("THBLAClassDict",(G__incsetup)(&G__cpp_setupTHBLAClassDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTHBLAClassDict() { G__remove_setup_func("THBLAClassDict"); }
};
G__cpp_setup_initTHBLAClassDict G__cpp_setup_initializerTHBLAClassDict;

