/********************************************************************
* dicts/Linux64RHEL7/TSCRCClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TSCRCClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSCRCClassDict();
extern void G__cpp_setup_inheritanceTSCRCClassDict();
extern void G__cpp_setup_typetableTSCRCClassDict();
extern void G__cpp_setup_memvarTSCRCClassDict();
extern void G__cpp_setup_globalTSCRCClassDict();
extern void G__cpp_setup_memfuncTSCRCClassDict();
extern void G__cpp_setup_funcTSCRCClassDict();
extern void G__set_cpp_environmentTSCRCClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSCRCClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSCRCClassDictLN_TClass;
extern G__linked_taginfo G__TSCRCClassDictLN_TBuffer;
extern G__linked_taginfo G__TSCRCClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TSCRCClassDictLN_TObject;
extern G__linked_taginfo G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSCRCClassDictLN_TSCRCClass;

/* STUB derived class for protected member access */
