//
// File generated by /u/apps/root/5.34.36/root/bin/rootcint at Tue Jan  9 15:26:34 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinux64RHEL7dITSCRCClassDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TSCRCClassDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TSCRCClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TSCRCClass(void *p = 0);
   static void *newArray_TSCRCClass(Long_t size, void *p);
   static void delete_TSCRCClass(void *p);
   static void deleteArray_TSCRCClass(void *p);
   static void destruct_TSCRCClass(void *p);
   static void streamer_TSCRCClass(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TSCRCClass*)
   {
      ::TSCRCClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSCRCClass >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TSCRCClass", ::TSCRCClass::Class_Version(), "./TSCRCClass.h", 23,
                  typeid(::TSCRCClass), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TSCRCClass::Dictionary, isa_proxy, 0,
                  sizeof(::TSCRCClass) );
      instance.SetNew(&new_TSCRCClass);
      instance.SetNewArray(&newArray_TSCRCClass);
      instance.SetDelete(&delete_TSCRCClass);
      instance.SetDeleteArray(&deleteArray_TSCRCClass);
      instance.SetDestructor(&destruct_TSCRCClass);
      instance.SetStreamerFunc(&streamer_TSCRCClass);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TSCRCClass*)
   {
      return GenerateInitInstanceLocal((::TSCRCClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TSCRCClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TSCRCClass::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TSCRCClass::Class_Name()
{
   return "TSCRCClass";
}

//______________________________________________________________________________
const char *TSCRCClass::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TSCRCClass*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TSCRCClass::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TSCRCClass*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TSCRCClass::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TSCRCClass*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TSCRCClass::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TSCRCClass*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TSCRCClass::Streamer(TBuffer &R__b)
{
   // Stream an object of class TSCRCClass.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> ID;
      R__b >> Energy;
      R__b >> dEnergy;
      R__b >> Time;
      R__b >> dTime;
      R__b >> X;
      R__b >> Y;
      R__b >> Z;
      R__b >> dX;
      R__b >> dY;
      R__b >> dZ;
      R__b >> Status;
      R__b >> sector;
      R__b.CheckByteCount(R__s, R__c, TSCRCClass::IsA());
   } else {
      R__c = R__b.WriteVersion(TSCRCClass::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << ID;
      R__b << Energy;
      R__b << dEnergy;
      R__b << Time;
      R__b << dTime;
      R__b << X;
      R__b << Y;
      R__b << Z;
      R__b << dX;
      R__b << dY;
      R__b << dZ;
      R__b << Status;
      R__b << sector;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TSCRCClass::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TSCRCClass.
      TClass *R__cl = ::TSCRCClass::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ID", &ID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Energy", &Energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dEnergy", &dEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Time", &Time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dTime", &dTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "X", &X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Y", &Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z", &Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dX", &dX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dY", &dY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dZ", &dZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Status", &Status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sector", &sector);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TSCRCClass(void *p) {
      return  p ? new(p) ::TSCRCClass : new ::TSCRCClass;
   }
   static void *newArray_TSCRCClass(Long_t nElements, void *p) {
      return p ? new(p) ::TSCRCClass[nElements] : new ::TSCRCClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_TSCRCClass(void *p) {
      delete ((::TSCRCClass*)p);
   }
   static void deleteArray_TSCRCClass(void *p) {
      delete [] ((::TSCRCClass*)p);
   }
   static void destruct_TSCRCClass(void *p) {
      typedef ::TSCRCClass current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TSCRCClass(TBuffer &buf, void *obj) {
      ((::TSCRCClass*)obj)->::TSCRCClass::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TSCRCClass

/********************************************************
* dicts/Linux64RHEL7/TSCRCClassDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTSCRCClassDict();

extern "C" void G__set_cpp_environmentTSCRCClassDict() {
  G__cpp_reset_tagtableTSCRCClassDict();
}
#include <new>
extern "C" int G__cpp_dllrevTSCRCClassDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TSCRCClass */
static int G__TSCRCClassDict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSCRCClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TSCRCClass[n];
     } else {
       p = new((void*) gvp) TSCRCClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TSCRCClass;
     } else {
       p = new((void*) gvp) TSCRCClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSCRCClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TSCRCClass((TSCRCClass*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TSCRCClass((TSCRCClass*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TSCRCClass*) G__getstructoffset())->GetSector());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TSCRCClass*) G__getstructoffset())->GetID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetdEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetdTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetdX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetdY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TSCRCClass*) G__getstructoffset())->GetdZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TSCRCClass*) G__getstructoffset())->GetStatus());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSCRCClass*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TSCRCClass::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSCRCClass::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TSCRCClass::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TSCRCClass::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSCRCClass*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSCRCClass::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSCRCClass::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSCRCClass::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSCRCClassDict_184_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSCRCClass::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TSCRCClassDict_184_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TSCRCClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TSCRCClass(*(TSCRCClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TSCRCClass G__TTSCRCClass;
static int G__TSCRCClassDict_184_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TSCRCClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TSCRCClass*) (soff+(sizeof(TSCRCClass)*i)))->~G__TTSCRCClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TSCRCClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TSCRCClass*) (soff))->~G__TTSCRCClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TSCRCClassDict_184_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSCRCClass* dest = (TSCRCClass*) G__getstructoffset();
   *dest = *(TSCRCClass*) libp->para[0].ref;
   const TSCRCClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TSCRCClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTSCRCClassDict {
 public:
  G__Sizep2memfuncTSCRCClassDict(): p(&G__Sizep2memfuncTSCRCClassDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTSCRCClassDict::*p)();
};

size_t G__get_sizep2memfuncTSCRCClassDict()
{
  G__Sizep2memfuncTSCRCClassDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTSCRCClassDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass))) {
     TSCRCClass *G__Lderived;
     G__Lderived=(TSCRCClass*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass),G__get_linked_tagnum(&G__TSCRCClassDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTSCRCClassDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TSCRCClass */
static void G__setup_memvarTSCRCClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass));
   { TSCRCClass *p; p=(TSCRCClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->ID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ID=",0,"id of the hit");
   G__memvar_setup((void*)((long)(&p->Energy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Energy=",0,"energy of the hit");
   G__memvar_setup((void*)((long)(&p->dEnergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dEnergy=",0,"error on energy");
   G__memvar_setup((void*)((long)(&p->Time)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Time=",0,"time");
   G__memvar_setup((void*)((long)(&p->dTime)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dTime=",0,"error in time");
   G__memvar_setup((void*)((long)(&p->X)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"X=",0,"X coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->Y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Y=",0,"Y coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Z=",0,"Z coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->dX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dX=",0,"error X coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->dY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dY=",0,"error Y coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->dZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dZ=",0,"error Z coordinate of the hit");
   G__memvar_setup((void*)((long)(&p->Status)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Status=",0,"Status word (not defined yet)");
   G__memvar_setup((void*)((long)(&p->sector)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"sector=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSCRCClassDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTSCRCClassDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTSCRCClass(void) {
   /* TSCRCClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass));
   G__memfunc_setup("TSCRCClass",885,G__TSCRCClassDict_184_0_1, 105, G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TSCRCClass",885,G__TSCRCClassDict_184_0_2, 105, G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass), -1, 0, 1, 1, 1, 0, "U 'TSCRCClass' - 0 - TmpSCRC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSector",912,G__TSCRCClassDict_184_0_3, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetID",429,G__TSCRCClassDict_184_0_4, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__TSCRCClassDict_184_0_5, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetdEnergy",1006,G__TSCRCClassDict_184_0_6, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__TSCRCClassDict_184_0_7, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetdTime",787,G__TSCRCClassDict_184_0_8, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetX",376,G__TSCRCClassDict_184_0_9, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetY",377,G__TSCRCClassDict_184_0_10, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZ",378,G__TSCRCClassDict_184_0_11, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetdX",476,G__TSCRCClassDict_184_0_12, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetdY",477,G__TSCRCClassDict_184_0_13, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetdZ",478,G__TSCRCClassDict_184_0_14, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStatus",932,G__TSCRCClassDict_184_0_15, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__TSCRCClassDict_184_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TSCRCClassDict_184_0_17, 85, G__get_linked_tagnum(&G__TSCRCClassDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TSCRCClass::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TSCRCClassDict_184_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSCRCClass::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TSCRCClassDict_184_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TSCRCClass::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TSCRCClassDict_184_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TSCRCClass::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TSCRCClassDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TSCRCClassDict_184_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TSCRCClassDict_184_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSCRCClass::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TSCRCClassDict_184_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSCRCClass::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TSCRCClassDict_184_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSCRCClass::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TSCRCClassDict_184_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSCRCClass::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TSCRCClass", 885, G__TSCRCClassDict_184_0_29, (int) ('i'), G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass), -1, 0, 1, 1, 1, 0, "u 'TSCRCClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TSCRCClass", 1011, G__TSCRCClassDict_184_0_30, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TSCRCClassDict_184_0_31, (int) ('u'), G__get_linked_tagnum(&G__TSCRCClassDictLN_TSCRCClass), -1, 1, 1, 1, 1, 0, "u 'TSCRCClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTSCRCClassDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTSCRCClassDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTSCRCClassDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TSCRCClassDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TSCRCClassDictLN_TSCRCClass = { "TSCRCClass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTSCRCClassDict() {
  G__TSCRCClassDictLN_TClass.tagnum = -1 ;
  G__TSCRCClassDictLN_TBuffer.tagnum = -1 ;
  G__TSCRCClassDictLN_TMemberInspector.tagnum = -1 ;
  G__TSCRCClassDictLN_TObject.tagnum = -1 ;
  G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TSCRCClassDictLN_TSCRCClass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTSCRCClassDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TSCRCClassDictLN_TSCRCClass),sizeof(TSCRCClass),-1,62720,"Class for accessing the SCPB bank: Time of Flight.",G__setup_memvarTSCRCClass,G__setup_memfuncTSCRCClass);
}
extern "C" void G__cpp_setupTSCRCClassDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTSCRCClassDict()");
  G__set_cpp_environmentTSCRCClassDict();
  G__cpp_setup_tagtableTSCRCClassDict();

  G__cpp_setup_inheritanceTSCRCClassDict();

  G__cpp_setup_typetableTSCRCClassDict();

  G__cpp_setup_memvarTSCRCClassDict();

  G__cpp_setup_memfuncTSCRCClassDict();
  G__cpp_setup_globalTSCRCClassDict();
  G__cpp_setup_funcTSCRCClassDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTSCRCClassDict();
  return;
}
class G__cpp_setup_initTSCRCClassDict {
  public:
    G__cpp_setup_initTSCRCClassDict() { G__add_setup_func("TSCRCClassDict",(G__incsetup)(&G__cpp_setupTSCRCClassDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTSCRCClassDict() { G__remove_setup_func("TSCRCClassDict"); }
};
G__cpp_setup_initTSCRCClassDict G__cpp_setup_initializerTSCRCClassDict;

