/********************************************************************
* dicts/Linux64RHEL7/TTBERClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TTBERClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTBERClassDict();
extern void G__cpp_setup_inheritanceTTBERClassDict();
extern void G__cpp_setup_typetableTTBERClassDict();
extern void G__cpp_setup_memvarTTBERClassDict();
extern void G__cpp_setup_globalTTBERClassDict();
extern void G__cpp_setup_memfuncTTBERClassDict();
extern void G__cpp_setup_funcTTBERClassDict();
extern void G__set_cpp_environmentTTBERClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTBERClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTBERClassDictLN_TClass;
extern G__linked_taginfo G__TTBERClassDictLN_TBuffer;
extern G__linked_taginfo G__TTBERClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TTBERClassDictLN_TObject;
extern G__linked_taginfo G__TTBERClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTBERClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTBERClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTBERClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTBERClassDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTBERClassDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTBERClassDictLN_TTBERClass;

/* STUB derived class for protected member access */
