/********************************************************************
* dicts/Linux/TCLASCorrectionBaseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TCLASCorrectionBaseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCLASCorrectionBaseDict();
extern void G__cpp_setup_inheritanceTCLASCorrectionBaseDict();
extern void G__cpp_setup_typetableTCLASCorrectionBaseDict();
extern void G__cpp_setup_memvarTCLASCorrectionBaseDict();
extern void G__cpp_setup_globalTCLASCorrectionBaseDict();
extern void G__cpp_setup_memfuncTCLASCorrectionBaseDict();
extern void G__cpp_setup_funcTCLASCorrectionBaseDict();
extern void G__set_cpp_environmentTCLASCorrectionBaseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCLASCorrectionBase.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TClass;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TBuffer;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMemberInspector;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TObject;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TLorentzVector;
extern G__linked_taginfo G__TCLASCorrectionBaseDictLN_TCLASCorrectionBase;

/* STUB derived class for protected member access */
