/********************************************************************
* dicts/Linux/TCLASCorrectionsG11ADict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TCLASCorrectionsG11ADict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCLASCorrectionsG11ADict();
extern void G__cpp_setup_inheritanceTCLASCorrectionsG11ADict();
extern void G__cpp_setup_typetableTCLASCorrectionsG11ADict();
extern void G__cpp_setup_memvarTCLASCorrectionsG11ADict();
extern void G__cpp_setup_globalTCLASCorrectionsG11ADict();
extern void G__cpp_setup_memfuncTCLASCorrectionsG11ADict();
extern void G__cpp_setup_funcTCLASCorrectionsG11ADict();
extern void G__set_cpp_environmentTCLASCorrectionsG11ADict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCLASCorrectionsG11A.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TClass;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TBuffer;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMemberInspector;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TObject;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TLorentzVector;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TCLASCorrectionBase;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TF1;
extern G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A;

/* STUB derived class for protected member access */
