/********************************************************************
* dicts/Linux/TCLASCorrectionsG10DDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TCLASCorrectionsG10DDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCLASCorrectionsG10DDict();
extern void G__cpp_setup_inheritanceTCLASCorrectionsG10DDict();
extern void G__cpp_setup_typetableTCLASCorrectionsG10DDict();
extern void G__cpp_setup_memvarTCLASCorrectionsG10DDict();
extern void G__cpp_setup_globalTCLASCorrectionsG10DDict();
extern void G__cpp_setup_memfuncTCLASCorrectionsG10DDict();
extern void G__cpp_setup_funcTCLASCorrectionsG10DDict();
extern void G__set_cpp_environmentTCLASCorrectionsG10DDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCLASCorrectionsG10D.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TClass;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TBuffer;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMemberInspector;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TObject;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TLorentzVector;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TCLASCorrectionBase;
extern G__linked_taginfo G__TCLASCorrectionsG10DDictLN_TCLASCorrectionsG10D;

/* STUB derived class for protected member access */
