//
// File generated by /apps/root/PRO/root/bin/rootcint at Fri Mar  3 10:10:26 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinuxdITCLASCorrectionsG11ADict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TCLASCorrectionsG11ADict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TCLASCorrectionsG11A_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TCLASCorrectionsG11A(void *p = 0);
   static void *newArray_TCLASCorrectionsG11A(Long_t size, void *p);
   static void delete_TCLASCorrectionsG11A(void *p);
   static void deleteArray_TCLASCorrectionsG11A(void *p);
   static void destruct_TCLASCorrectionsG11A(void *p);
   static void streamer_TCLASCorrectionsG11A(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TCLASCorrectionsG11A*)
   {
      ::TCLASCorrectionsG11A *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TCLASCorrectionsG11A >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TCLASCorrectionsG11A", ::TCLASCorrectionsG11A::Class_Version(), "./TCLASCorrectionsG11A.h", 21,
                  typeid(::TCLASCorrectionsG11A), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TCLASCorrectionsG11A::Dictionary, isa_proxy, 0,
                  sizeof(::TCLASCorrectionsG11A) );
      instance.SetNew(&new_TCLASCorrectionsG11A);
      instance.SetNewArray(&newArray_TCLASCorrectionsG11A);
      instance.SetDelete(&delete_TCLASCorrectionsG11A);
      instance.SetDeleteArray(&deleteArray_TCLASCorrectionsG11A);
      instance.SetDestructor(&destruct_TCLASCorrectionsG11A);
      instance.SetStreamerFunc(&streamer_TCLASCorrectionsG11A);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TCLASCorrectionsG11A*)
   {
      return GenerateInitInstanceLocal((::TCLASCorrectionsG11A*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TCLASCorrectionsG11A*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TCLASCorrectionsG11A::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TCLASCorrectionsG11A::Class_Name()
{
   return "TCLASCorrectionsG11A";
}

//______________________________________________________________________________
const char *TCLASCorrectionsG11A::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TCLASCorrectionsG11A*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TCLASCorrectionsG11A::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TCLASCorrectionsG11A*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TCLASCorrectionsG11A::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TCLASCorrectionsG11A*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TCLASCorrectionsG11A::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TCLASCorrectionsG11A*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TCLASCorrectionsG11A::Streamer(TBuffer &R__b)
{
   // Stream an object of class TCLASCorrectionsG11A.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TCLASCorrectionBase::Streamer(R__b);
      R__b >> func_P3;
      R__b >> func_P4;
      R__b.CheckByteCount(R__s, R__c, TCLASCorrectionsG11A::IsA());
   } else {
      R__c = R__b.WriteVersion(TCLASCorrectionsG11A::IsA(), kTRUE);
      TCLASCorrectionBase::Streamer(R__b);
      R__b << func_P3;
      R__b << func_P4;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TCLASCorrectionsG11A::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TCLASCorrectionsG11A.
      TClass *R__cl = ::TCLASCorrectionsG11A::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*func_P3", &func_P3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*func_P4", &func_P4);
      TCLASCorrectionBase::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TCLASCorrectionsG11A(void *p) {
      return  p ? new(p) ::TCLASCorrectionsG11A : new ::TCLASCorrectionsG11A;
   }
   static void *newArray_TCLASCorrectionsG11A(Long_t nElements, void *p) {
      return p ? new(p) ::TCLASCorrectionsG11A[nElements] : new ::TCLASCorrectionsG11A[nElements];
   }
   // Wrapper around operator delete
   static void delete_TCLASCorrectionsG11A(void *p) {
      delete ((::TCLASCorrectionsG11A*)p);
   }
   static void deleteArray_TCLASCorrectionsG11A(void *p) {
      delete [] ((::TCLASCorrectionsG11A*)p);
   }
   static void destruct_TCLASCorrectionsG11A(void *p) {
      typedef ::TCLASCorrectionsG11A current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TCLASCorrectionsG11A(TBuffer &buf, void *obj) {
      ((::TCLASCorrectionsG11A*)obj)->::TCLASCorrectionsG11A::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TCLASCorrectionsG11A

/********************************************************
* dicts/Linux/TCLASCorrectionsG11ADict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTCLASCorrectionsG11ADict();

extern "C" void G__set_cpp_environmentTCLASCorrectionsG11ADict() {
  G__cpp_reset_tagtableTCLASCorrectionsG11ADict();
}
#include <new>
extern "C" int G__cpp_dllrevTCLASCorrectionsG11ADict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TCLASCorrectionsG11A */
static int G__TCLASCorrectionsG11ADict_286_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCLASCorrectionsG11A* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCLASCorrectionsG11A[n];
     } else {
       p = new((void*) gvp) TCLASCorrectionsG11A[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCLASCorrectionsG11A;
     } else {
       p = new((void*) gvp) TCLASCorrectionsG11A;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetLambdaTrack((double*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetPhiTrack((double*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetFunc_p((double) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetFunc_phi((double) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetFunc_lam((double) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCLASCorrectionsG11A*) G__getstructoffset())->GetFuncLambda((TF1*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCLASCorrectionsG11A*) G__getstructoffset())->SetP3FromTrackingParameters((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (double*) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetSectorPhi((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetBin((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TCLASCorrectionsG11A*) G__getstructoffset())->GetSector((double*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TCLASCorrectionsG11A::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCLASCorrectionsG11A::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TCLASCorrectionsG11A::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TCLASCorrectionsG11A::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCLASCorrectionsG11A*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCLASCorrectionsG11A::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCLASCorrectionsG11A::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCLASCorrectionsG11A::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TCLASCorrectionsG11ADict_286_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCLASCorrectionsG11A::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TCLASCorrectionsG11ADict_286_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TCLASCorrectionsG11A* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TCLASCorrectionsG11A(*(TCLASCorrectionsG11A*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TCLASCorrectionsG11A G__TTCLASCorrectionsG11A;
static int G__TCLASCorrectionsG11ADict_286_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TCLASCorrectionsG11A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TCLASCorrectionsG11A*) (soff+(sizeof(TCLASCorrectionsG11A)*i)))->~G__TTCLASCorrectionsG11A();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TCLASCorrectionsG11A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TCLASCorrectionsG11A*) (soff))->~G__TTCLASCorrectionsG11A();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TCLASCorrectionsG11ADict_286_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCLASCorrectionsG11A* dest = (TCLASCorrectionsG11A*) G__getstructoffset();
   *dest = *(TCLASCorrectionsG11A*) libp->para[0].ref;
   const TCLASCorrectionsG11A& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TCLASCorrectionsG11A */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTCLASCorrectionsG11ADict {
 public:
  G__Sizep2memfuncTCLASCorrectionsG11ADict(): p(&G__Sizep2memfuncTCLASCorrectionsG11ADict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTCLASCorrectionsG11ADict::*p)();
};

size_t G__get_sizep2memfuncTCLASCorrectionsG11ADict()
{
  G__Sizep2memfuncTCLASCorrectionsG11ADict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTCLASCorrectionsG11ADict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A))) {
     TCLASCorrectionsG11A *G__Lderived;
     G__Lderived=(TCLASCorrectionsG11A*)0x1000;
     {
       TCLASCorrectionBase *G__Lpbase=(TCLASCorrectionBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A),G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A),G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTCLASCorrectionsG11ADict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TCLASCorrectionsG11A */
static void G__setup_memvarTCLASCorrectionsG11A(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A));
   { TCLASCorrectionsG11A *p; p=(TCLASCorrectionsG11A*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TF1),-1,-1,4,"func_P3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TF1),-1,-1,4,"func_P4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTCLASCorrectionsG11ADict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTCLASCorrectionsG11A(void) {
   /* TCLASCorrectionsG11A */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A));
   G__memfunc_setup("TCLASCorrectionsG11A",1772,G__TCLASCorrectionsG11ADict_286_0_1, 105, G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetVector",915,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TLorentzVector), -1, 0, 3, 1, 1, 0, 
"u 'TLorentzVector' - 0 - vPin i - - 0 - charge "
"i - - 0 - type", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTagger",890,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TLorentzVector), -1, 0, 3, 1, 1, 0, 
"u 'TLorentzVector' - 0 - vG i - - 0 - E_ID "
"i - - 0 - RunNum", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLambdaTrack",1366,G__TCLASCorrectionsG11ADict_286_0_5, 100, -1, -1, 0, 1, 1, 1, 0, "D - - 0 - v3_", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPhiTrack",1078,G__TCLASCorrectionsG11ADict_286_0_6, 100, -1, -1, 0, 1, 1, 1, 0, "D - - 0 - v3_", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFunc_p",891,G__TCLASCorrectionsG11ADict_286_0_7, 100, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - _p i - - 0 - charge "
"i - - 0 - bin i - - 0 - sector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFunc_phi",1100,G__TCLASCorrectionsG11ADict_286_0_8, 100, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - _p i - - 0 - charge "
"i - - 0 - bin i - - 0 - sector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFunc_lam",1093,G__TCLASCorrectionsG11ADict_286_0_9, 100, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - _p i - - 0 - charge "
"i - - 0 - bin i - - 0 - sector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFuncLambda",1261,G__TCLASCorrectionsG11ADict_286_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TF1' - 0 - f1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetP3FromTrackingParameters",2698,G__TCLASCorrectionsG11ADict_286_0_11, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - - 0 - __p d - - 0 - __lam "
"d - - 0 - __phi i - - 0 - __sector "
"D - - 0 - __p3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSectorPhi",1201,G__TCLASCorrectionsG11ADict_286_0_12, 100, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - __phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBin",569,G__TCLASCorrectionsG11ADict_286_0_13, 105, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - __theta d - - 0 - __phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSector",912,G__TCLASCorrectionsG11ADict_286_0_14, 105, -1, -1, 0, 1, 1, 1, 0, "D - - 0 - __p3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TCLASCorrectionsG11ADict_286_0_15, 85, G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TCLASCorrectionsG11A::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TCLASCorrectionsG11ADict_286_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCLASCorrectionsG11A::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TCLASCorrectionsG11ADict_286_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TCLASCorrectionsG11A::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TCLASCorrectionsG11ADict_286_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TCLASCorrectionsG11A::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TCLASCorrectionsG11ADict_286_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TCLASCorrectionsG11ADict_286_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCLASCorrectionsG11A::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TCLASCorrectionsG11ADict_286_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCLASCorrectionsG11A::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TCLASCorrectionsG11ADict_286_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCLASCorrectionsG11A::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TCLASCorrectionsG11ADict_286_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCLASCorrectionsG11A::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TCLASCorrectionsG11A", 1772, G__TCLASCorrectionsG11ADict_286_0_27, (int) ('i'), G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A), -1, 0, 1, 1, 1, 0, "u 'TCLASCorrectionsG11A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TCLASCorrectionsG11A", 1898, G__TCLASCorrectionsG11ADict_286_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TCLASCorrectionsG11ADict_286_0_29, (int) ('u'), G__get_linked_tagnum(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A), -1, 1, 1, 1, 1, 0, "u 'TCLASCorrectionsG11A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTCLASCorrectionsG11ADict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTCLASCorrectionsG11ADict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTCLASCorrectionsG11ADict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TCLASCorrectionBase = { "TCLASCorrectionBase" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A = { "TCLASCorrectionsG11A" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTCLASCorrectionsG11ADict() {
  G__TCLASCorrectionsG11ADictLN_TClass.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TBuffer.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMemberInspector.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TObject.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TLorentzVector.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TCLASCorrectionBase.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TF1.tagnum = -1 ;
  G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTCLASCorrectionsG11ADict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionBase);
   G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TF1);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TCLASCorrectionsG11ADictLN_TCLASCorrectionsG11A),sizeof(TCLASCorrectionsG11A),-1,29952,(char*)NULL,G__setup_memvarTCLASCorrectionsG11A,G__setup_memfuncTCLASCorrectionsG11A);
}
extern "C" void G__cpp_setupTCLASCorrectionsG11ADict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTCLASCorrectionsG11ADict()");
  G__set_cpp_environmentTCLASCorrectionsG11ADict();
  G__cpp_setup_tagtableTCLASCorrectionsG11ADict();

  G__cpp_setup_inheritanceTCLASCorrectionsG11ADict();

  G__cpp_setup_typetableTCLASCorrectionsG11ADict();

  G__cpp_setup_memvarTCLASCorrectionsG11ADict();

  G__cpp_setup_memfuncTCLASCorrectionsG11ADict();
  G__cpp_setup_globalTCLASCorrectionsG11ADict();
  G__cpp_setup_funcTCLASCorrectionsG11ADict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTCLASCorrectionsG11ADict();
  return;
}
class G__cpp_setup_initTCLASCorrectionsG11ADict {
  public:
    G__cpp_setup_initTCLASCorrectionsG11ADict() { G__add_setup_func("TCLASCorrectionsG11ADict",(G__incsetup)(&G__cpp_setupTCLASCorrectionsG11ADict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTCLASCorrectionsG11ADict() { G__remove_setup_func("TCLASCorrectionsG11ADict"); }
};
G__cpp_setup_initTCLASCorrectionsG11ADict G__cpp_setup_initializerTCLASCorrectionsG11ADict;

