/********************************************************************
* dicts/Linux/TCLASCorrectionsGSIMDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TCLASCorrectionsGSIMDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_inheritanceTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_typetableTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_memvarTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_globalTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_memfuncTCLASCorrectionsGSIMDict();
extern void G__cpp_setup_funcTCLASCorrectionsGSIMDict();
extern void G__set_cpp_environmentTCLASCorrectionsGSIMDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCLASCorrectionsGSIM.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TClass;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TBuffer;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMemberInspector;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TObject;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TLorentzVector;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TCLASCorrectionBase;
extern G__linked_taginfo G__TCLASCorrectionsGSIMDictLN_TCLASCorrectionsGSIM;

/* STUB derived class for protected member access */
