/********************************************************************
* dicts/Linux/TFuncInterceptDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux/TFuncInterceptDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFuncInterceptDict();
extern void G__cpp_setup_inheritanceTFuncInterceptDict();
extern void G__cpp_setup_typetableTFuncInterceptDict();
extern void G__cpp_setup_memvarTFuncInterceptDict();
extern void G__cpp_setup_globalTFuncInterceptDict();
extern void G__cpp_setup_memfuncTFuncInterceptDict();
extern void G__cpp_setup_funcTFuncInterceptDict();
extern void G__set_cpp_environmentTFuncInterceptDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TFuncIntercept.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFuncInterceptDictLN_TClass;
extern G__linked_taginfo G__TFuncInterceptDictLN_TBuffer;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMemberInspector;
extern G__linked_taginfo G__TFuncInterceptDictLN_TObject;
extern G__linked_taginfo G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TFuncInterceptDictLN_TFuncIntercept;

/* STUB derived class for protected member access */
