//
// File generated by /apps/root/PRO/root/bin/rootcint at Fri Mar  3 10:10:23 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinuxdITFuncInterceptDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TFuncInterceptDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TFuncIntercept_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TFuncIntercept(void *p = 0);
   static void *newArray_TFuncIntercept(Long_t size, void *p);
   static void delete_TFuncIntercept(void *p);
   static void deleteArray_TFuncIntercept(void *p);
   static void destruct_TFuncIntercept(void *p);
   static void streamer_TFuncIntercept(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TFuncIntercept*)
   {
      ::TFuncIntercept *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TFuncIntercept >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TFuncIntercept", ::TFuncIntercept::Class_Version(), "./TFuncIntercept.h", 15,
                  typeid(::TFuncIntercept), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TFuncIntercept::Dictionary, isa_proxy, 0,
                  sizeof(::TFuncIntercept) );
      instance.SetNew(&new_TFuncIntercept);
      instance.SetNewArray(&newArray_TFuncIntercept);
      instance.SetDelete(&delete_TFuncIntercept);
      instance.SetDeleteArray(&deleteArray_TFuncIntercept);
      instance.SetDestructor(&destruct_TFuncIntercept);
      instance.SetStreamerFunc(&streamer_TFuncIntercept);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TFuncIntercept*)
   {
      return GenerateInitInstanceLocal((::TFuncIntercept*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TFuncIntercept*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TFuncIntercept::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TFuncIntercept::Class_Name()
{
   return "TFuncIntercept";
}

//______________________________________________________________________________
const char *TFuncIntercept::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TFuncIntercept*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TFuncIntercept::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TFuncIntercept*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TFuncIntercept::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TFuncIntercept*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TFuncIntercept::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TFuncIntercept*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TFuncIntercept::Streamer(TBuffer &R__b)
{
   // Stream an object of class TFuncIntercept.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, TFuncIntercept::IsA());
   } else {
      R__c = R__b.WriteVersion(TFuncIntercept::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TFuncIntercept::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TFuncIntercept.
      TClass *R__cl = ::TFuncIntercept::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TFuncIntercept(void *p) {
      return  p ? new(p) ::TFuncIntercept : new ::TFuncIntercept;
   }
   static void *newArray_TFuncIntercept(Long_t nElements, void *p) {
      return p ? new(p) ::TFuncIntercept[nElements] : new ::TFuncIntercept[nElements];
   }
   // Wrapper around operator delete
   static void delete_TFuncIntercept(void *p) {
      delete ((::TFuncIntercept*)p);
   }
   static void deleteArray_TFuncIntercept(void *p) {
      delete [] ((::TFuncIntercept*)p);
   }
   static void destruct_TFuncIntercept(void *p) {
      typedef ::TFuncIntercept current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TFuncIntercept(TBuffer &buf, void *obj) {
      ((::TFuncIntercept*)obj)->::TFuncIntercept::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TFuncIntercept

/********************************************************
* dicts/Linux/TFuncInterceptDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTFuncInterceptDict();

extern "C" void G__set_cpp_environmentTFuncInterceptDict() {
  G__cpp_reset_tagtableTFuncInterceptDict();
}
#include <new>
extern "C" int G__cpp_dllrevTFuncInterceptDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TFuncIntercept */
static int G__TFuncInterceptDict_253_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TFuncIntercept* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TFuncIntercept[n];
     } else {
       p = new((void*) gvp) TFuncIntercept[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TFuncIntercept;
     } else {
       p = new((void*) gvp) TFuncIntercept;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->InterCylinder(
(double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]), (double*) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double*) G__int(libp->para[5])
, (int*) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->IntersectionPlane((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]), (double*) G__int(libp->para[3])
, (double*) G__int(libp->para[4]), (int*) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->IntersectionSphere(
(double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]), (double) G__double(libp->para[3])
, (double*) G__int(libp->para[4]), (double*) G__int(libp->para[5])
, (int*) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->IntersectionCone(
(double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]), (double*) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double*) G__int(libp->para[5])
, (double*) G__int(libp->para[6]), (int*) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->IntersectionCylindre(
(double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]), (double*) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double*) G__int(libp->para[5])
, (double*) G__int(libp->para[6]), (int*) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TFuncIntercept::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFuncIntercept::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TFuncIntercept::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TFuncIntercept::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFuncIntercept*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFuncIntercept::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TFuncIntercept::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFuncIntercept::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFuncInterceptDict_253_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TFuncIntercept::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TFuncInterceptDict_253_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TFuncIntercept* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TFuncIntercept(*(TFuncIntercept*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TFuncIntercept G__TTFuncIntercept;
static int G__TFuncInterceptDict_253_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TFuncIntercept*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TFuncIntercept*) (soff+(sizeof(TFuncIntercept)*i)))->~G__TTFuncIntercept();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TFuncIntercept*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TFuncIntercept*) (soff))->~G__TTFuncIntercept();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TFuncInterceptDict_253_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TFuncIntercept* dest = (TFuncIntercept*) G__getstructoffset();
   *dest = *(TFuncIntercept*) libp->para[0].ref;
   const TFuncIntercept& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TFuncIntercept */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTFuncInterceptDict {
 public:
  G__Sizep2memfuncTFuncInterceptDict(): p(&G__Sizep2memfuncTFuncInterceptDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTFuncInterceptDict::*p)();
};

size_t G__get_sizep2memfuncTFuncInterceptDict()
{
  G__Sizep2memfuncTFuncInterceptDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTFuncInterceptDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept))) {
     TFuncIntercept *G__Lderived;
     G__Lderived=(TFuncIntercept*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept),G__get_linked_tagnum(&G__TFuncInterceptDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTFuncInterceptDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TFuncIntercept */
static void G__setup_memvarTFuncIntercept(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept));
   { TFuncIntercept *p; p=(TFuncIntercept*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TFuncInterceptDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTFuncInterceptDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTFuncIntercept(void) {
   /* TFuncIntercept */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept));
   G__memfunc_setup("TFuncIntercept",1422,G__TFuncInterceptDict_253_0_1, 105, G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InterCylinder",1340,G__TFuncInterceptDict_253_0_2, 121, -1, -1, 0, 7, 1, 1, 0, 
"D - - 0 - vertex D - - 0 - cdir "
"D - - 0 - center D - - 0 - d "
"d - - 0 - r D - - 0 - x "
"I - - 0 - ierr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IntersectionPlane",1767,G__TFuncInterceptDict_253_0_3, 121, -1, -1, 0, 6, 1, 1, 0, 
"D - - 0 - m1 D - - 0 - m2 "
"D - - 0 - m0 D - - 0 - n "
"D - - 0 - m I - - 0 - rep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IntersectionSphere",1886,G__TFuncInterceptDict_253_0_4, 121, -1, -1, 0, 7, 1, 1, 0, 
"D - - 0 - m1 D - - 0 - m2 "
"D - - 0 - m0 d - - 0 - r "
"D - - 0 - m D - - 0 - mm "
"I - - 0 - rep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IntersectionCone",1660,G__TFuncInterceptDict_253_0_5, 121, -1, -1, 0, 8, 1, 1, 0, 
"D - - 0 - m1 D - - 0 - m2 "
"D - - 0 - m0 D - - 0 - d "
"d - - 0 - alpha D - - 0 - m "
"D - - 0 - mm I - - 0 - rep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IntersectionCylindre",2097,G__TFuncInterceptDict_253_0_6, 121, -1, -1, 0, 8, 1, 1, 0, 
"D - - 0 - m1 D - - 0 - m2 "
"D - - 0 - m0 D - - 0 - d "
"d - - 0 - r D - - 0 - m "
"D - - 0 - mm I - - 0 - rep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TFuncInterceptDict_253_0_7, 85, G__get_linked_tagnum(&G__TFuncInterceptDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TFuncIntercept::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TFuncInterceptDict_253_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFuncIntercept::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TFuncInterceptDict_253_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TFuncIntercept::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TFuncInterceptDict_253_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TFuncIntercept::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TFuncInterceptDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TFuncInterceptDict_253_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TFuncInterceptDict_253_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFuncIntercept::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TFuncInterceptDict_253_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TFuncIntercept::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TFuncInterceptDict_253_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFuncIntercept::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TFuncInterceptDict_253_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TFuncIntercept::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TFuncIntercept", 1422, G__TFuncInterceptDict_253_0_19, (int) ('i'), G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept), -1, 0, 1, 1, 1, 0, "u 'TFuncIntercept' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TFuncIntercept", 1548, G__TFuncInterceptDict_253_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TFuncInterceptDict_253_0_21, (int) ('u'), G__get_linked_tagnum(&G__TFuncInterceptDictLN_TFuncIntercept), -1, 1, 1, 1, 1, 0, "u 'TFuncIntercept' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTFuncInterceptDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTFuncInterceptDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTFuncInterceptDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TFuncInterceptDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TFuncInterceptDictLN_TFuncIntercept = { "TFuncIntercept" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTFuncInterceptDict() {
  G__TFuncInterceptDictLN_TClass.tagnum = -1 ;
  G__TFuncInterceptDictLN_TBuffer.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMemberInspector.tagnum = -1 ;
  G__TFuncInterceptDictLN_TObject.tagnum = -1 ;
  G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TFuncInterceptDictLN_TFuncIntercept.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTFuncInterceptDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TFuncInterceptDictLN_TFuncIntercept),sizeof(TFuncIntercept),-1,29952,(char*)NULL,G__setup_memvarTFuncIntercept,G__setup_memfuncTFuncIntercept);
}
extern "C" void G__cpp_setupTFuncInterceptDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTFuncInterceptDict()");
  G__set_cpp_environmentTFuncInterceptDict();
  G__cpp_setup_tagtableTFuncInterceptDict();

  G__cpp_setup_inheritanceTFuncInterceptDict();

  G__cpp_setup_typetableTFuncInterceptDict();

  G__cpp_setup_memvarTFuncInterceptDict();

  G__cpp_setup_memfuncTFuncInterceptDict();
  G__cpp_setup_globalTFuncInterceptDict();
  G__cpp_setup_funcTFuncInterceptDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTFuncInterceptDict();
  return;
}
class G__cpp_setup_initTFuncInterceptDict {
  public:
    G__cpp_setup_initTFuncInterceptDict() { G__add_setup_func("TFuncInterceptDict",(G__incsetup)(&G__cpp_setupTFuncInterceptDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTFuncInterceptDict() { G__remove_setup_func("TFuncInterceptDict"); }
};
G__cpp_setup_initTFuncInterceptDict G__cpp_setup_initializerTFuncInterceptDict;

